### ISSUE TITLE
Notlar

### ISSUE THREAD

**Issue by ertseyhan** [grknylmz/IleriCveSistemProgramlama#1]
Burada kurs notlarını ve örneklerini public olarak paylaşmanıza istinaden fork oluşturdum. Yine'de sormak istiyorum. Kurs notlarından ve bulut hesabınızda mevcut olan kurs örneklerinden faydalanmak niyetindeyim. Sizin için bir sorun teşkil eder mi?

**Comment by grknylmz** [comment]
Github'ın amacı paylaşmak zaten :) istediğiniz gibi takılabilirsiniz.

**Comment by ertseyhan** [comment]
Teşekkürler.
